version: '3.3'
services:
    rdtclient:
        image: rogerfar/rdtclient
        volumes:
            - ./data/downloads:/data/downloads
            - ./data/db:/data/db
        container_name: rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'
